### ISSUE TITLE
Dependencies with version latest are not replaced

### ISSUE THREAD

**Issue by SuperSandro2000** [adisbladis/buildNodeModules#1]
I tried to test this on bitwarden-desktop which has some dependencies with version latest. https://github.com/bitwarden/clients/blob/desktop-v2023.10.1/package-lock.json#L5121-L5130

which does not seem to work

```
Installing patched package.json/package-lock.json
Installing dependencies
npm ERR! code ENOTCACHED
npm ERR! request to https://registry.npmjs.org/cors failed: cache mode is 'only-if-cached' but no cached response is available.

npm ERR! A complete log of this run can be found in: /build/.npm/_logs/2023-11-21T11_14_48_560Z-debug-0.log

ERROR: npm failed to install dependencies

Here are a few things you can try, depending on the error:
1. Set `npmFlags = [ "--legacy-peer-deps" ]`

note: keeping build directory '/tmp/nix-build-bitwarden-2023.10.1.drv-1'
```

npm log

```
0 verbose cli /nix/store/4bgg8j8275adawqbc5rkm4fv48dgg2i3-nodejs-18.18.2/bin/node /nix/store/4bgg8j8275adawqbc5rkm4fv48dgg2i3-nodejs-18.18.2/bin/npm
1 info using npm@9.8.1
2 info using node@v18.18.2
3 timing npm:load:whichnode Completed in 1ms
4 timing config:load:defaults Completed in 2ms
5 timing config:load:file:/nix/store/4bgg8j8275adawqbc5rkm4fv48dgg2i3-nodejs-18.18.2/lib/node_modules/npm/npmrc Completed in 0ms
6 timing config:load:builtin Completed in 0ms
7 timing config:load:cli Completed in 3ms
8 timing config:load:env Completed in 0ms
9 timing config:load:file:/build/source/.npmrc Completed in 0ms
10 timing config:load:project Completed in 16ms
11 timing config:load:file:/build/.npmrc Completed in 1ms
12 timing config:load:user Completed in 1ms
13 timing config:load:file:/nix/store/4bgg8j8275adawqbc5rkm4fv48dgg2i3-nodejs-18.18.2/etc/npmrc Completed in 0ms
14 timing config:load:global Completed in 0ms
15 timing config:load:setEnvs Completed in 0ms
16 timing config:load Completed in 24ms
17 timing npm:load:configload Completed in 24ms
18 timing config:load:flatten Completed in 2ms
19 timing npm:load:mkdirpcache Completed in 1ms
20 timing npm:load:mkdirplogs Completed in 0ms
21 verbose title npm install
22 verbose argv "install" "--ignore-scripts"
23 timing npm:load:setTitle Completed in 1ms
24 timing npm:load:display Completed in 0ms
25 verbose logfile logs-max:10 dir:/build/.npm/_logs/2023-11-21T11_10_45_160Z-
26 verbose logfile /build/.npm/_logs/2023-11-21T11_10_45_160Z-debug-0.log
27 timing npm:load:logFile Completed in 3ms
28 timing npm:load:timers Completed in 0ms
29 timing npm:load:configScope Completed in 0ms
30 timing npm:load Completed in 45ms
31 timing arborist:ctor Completed in 1ms
32 silly logfile done cleaning log files
33 timing idealTree:init Completed in 4783ms
34 timing idealTree:userRequests Completed in 1ms
35 silly idealTree buildDeps
36 silly placeDep ROOT @bitwarden/angular@0.0.0 REPLACE for: @bitwarden/clients@0.0.0 want: file:/build/source/libs/angular
37 silly placeDep ROOT @bitwarden/auth@0.0.0 REPLACE for: @bitwarden/clients@0.0.0 want: file:/build/source/libs/auth
38 silly placeDep ROOT @bitwarden/browser@2023.10.1 REPLACE for: @bitwarden/clients@0.0.0 want: file:/build/source/apps/browser
39 silly placeDep ROOT @bitwarden/cli@2023.10.0 REPLACE for: @bitwarden/clients@0.0.0 want: file:/build/source/apps/cli
40 silly placeDep ROOT @bitwarden/common@0.0.0 REPLACE for: @bitwarden/clients@0.0.0 want: file:/build/source/libs/common
41 silly placeDep ROOT @bitwarden/components@0.0.0 REPLACE for: @bitwarden/clients@0.0.0 want: file:/build/source/libs/components
42 silly placeDep ROOT @bitwarden/desktop@2023.10.1 REPLACE for: @bitwarden/clients@0.0.0 want: file:/build/source/apps/desktop
43 silly placeDep ROOT @bitwarden/desktop-native@0.1.0 REPLACE for: @bitwarden/clients@0.0.0 want: file:/build/source/apps/desktop/desktop_native
44 silly placeDep ROOT @bitwarden/exporter@0.0.0 REPLACE for: @bitwarden/clients@0.0.0 want: file:/build/source/libs/exporter
45 silly placeDep ROOT @bitwarden/importer@0.0.0 REPLACE for: @bitwarden/clients@0.0.0 want: file:/build/source/libs/importer
46 silly placeDep ROOT @bitwarden/node@0.0.0 REPLACE for: @bitwarden/clients@0.0.0 want: file:/build/source/libs/node
47 silly placeDep ROOT @bitwarden/vault@0.0.0 REPLACE for: @bitwarden/clients@0.0.0 want: file:/build/source/libs/vault
48 silly placeDep ROOT @bitwarden/web-vault@2023.10.0 REPLACE for: @bitwarden/clients@0.0.0 want: file:/build/source/apps/web
49 silly placeDep ROOT duo_web_sdk@2.7.0 REPLACE for: @bitwarden/clients@0.0.0 want: file:/nix/store/g0zna0kxdql7lgyh6wqkc2hw9ap1laqg-source
50 timing idealTree:#root Completed in 265ms
51 timing idealTree:node_modules/@bitwarden/angular Completed in 0ms
52 timing idealTree:node_modules/@bitwarden/auth Completed in 0ms
53 timing idealTree:node_modules/@bitwarden/browser Completed in 0ms
54 timing idealTree:node_modules/@bitwarden/cli Completed in 0ms
55 timing idealTree:node_modules/@bitwarden/common Completed in 0ms
56 timing idealTree:node_modules/@bitwarden/components Completed in 0ms
57 timing idealTree:node_modules/@bitwarden/desktop Completed in 0ms
58 timing idealTree:node_modules/@bitwarden/desktop-native Completed in 0ms
59 timing idealTree:node_modules/@bitwarden/exporter Completed in 0ms
60 timing idealTree:node_modules/@bitwarden/importer Completed in 0ms
61 timing idealTree:node_modules/@bitwarden/node Completed in 0ms
62 timing idealTree:node_modules/@bitwarden/vault Completed in 0ms
63 timing idealTree:node_modules/@bitwarden/web-vault Completed in 0ms
64 silly fetch manifest cors@latest
65 silly fetch manifest object-assign@latest
66 silly fetch manifest proxy-middleware@latest
67 silly fetch manifest send@latest
68 silly placeDep node_modules/@compodoc/live-server cors@ OK for: @compodoc/live-server@1.2.3 want: latest
69 silly placeDep node_modules/@compodoc/live-server object-assign@ OK for: @compodoc/live-server@1.2.3 want: latest
70 silly placeDep node_modules/@compodoc/live-server proxy-middleware@ OK for: @compodoc/live-server@1.2.3 want: latest
71 silly placeDep node_modules/@compodoc/live-server send@ OK for: @compodoc/live-server@1.2.3 want: latest
72 timing idealTree:node_modules/@compodoc/live-server Completed in 40ms
73 timing idealTree:node_modules/duo_web_sdk Completed in 0ms
74 timing idealTree:node_modules/@compodoc/live-server/node_modules/cors Completed in 0ms
75 timing idealTree:node_modules/@compodoc/live-server/node_modules/object-assign Completed in 0ms
76 timing idealTree:node_modules/@compodoc/live-server/node_modules/proxy-middleware Completed in 0ms
77 timing idealTree:node_modules/@compodoc/live-server/node_modules/send Completed in 0ms
78 timing idealTree:apps/browser Completed in 0ms
79 timing idealTree:apps/cli Completed in 8ms
80 timing idealTree:apps/desktop Completed in 0ms
81 timing idealTree:apps/desktop/desktop_native Completed in 0ms
82 timing idealTree:apps/web Completed in 0ms
83 timing idealTree:libs/angular Completed in 0ms
84 timing idealTree:libs/auth Completed in 0ms
85 timing idealTree:libs/common Completed in 0ms
86 timing idealTree:libs/components Completed in 0ms
87 timing idealTree:libs/exporter Completed in 0ms
88 timing idealTree:libs/importer Completed in 0ms
89 timing idealTree:libs/node Completed in 0ms
90 timing idealTree:libs/vault Completed in 0ms
91 timing idealTree:buildDeps Completed in 326ms
92 timing idealTree:fixDepFlags Completed in 50ms
93 timing idealTree Completed in 5163ms
94 timing command:install Completed in 5169ms
95 verbose stack Error: request to https://registry.npmjs.org/cors failed: cache mode is 'only-if-cached' but no cached response is available.
95 verbose stack     at cacheFetch (/nix/store/4bgg8j8275adawqbc5rkm4fv48dgg2i3-nodejs-18.18.2/lib/node_modules/npm/node_modules/make-fetch-happen/lib/cache/index.js:12:13)
95 verbose stack     at async fetch (/nix/store/4bgg8j8275adawqbc5rkm4fv48dgg2i3-nodejs-18.18.2/lib/node_modules/npm/node_modules/make-fetch-happen/lib/fetch.js:98:7)
95 verbose stack     at async RegistryFetcher.packument (/nix/store/4bgg8j8275adawqbc5rkm4fv48dgg2i3-nodejs-18.18.2/lib/node_modules/npm/node_modules/pacote/lib/registry.js:87:19)
95 verbose stack     at async RegistryFetcher.manifest (/nix/store/4bgg8j8275adawqbc5rkm4fv48dgg2i3-nodejs-18.18.2/lib/node_modules/npm/node_modules/pacote/lib/registry.js:118:23)
95 verbose stack     at async #nodeFromEdge (/nix/store/4bgg8j8275adawqbc5rkm4fv48dgg2i3-nodejs-18.18.2/lib/node_modules/npm/node_modules/@npmcli/arborist/lib/arborist/build-ideal-tree.js:10
49:19)
95 verbose stack     at async #buildDepStep (/nix/store/4bgg8j8275adawqbc5rkm4fv48dgg2i3-nodejs-18.18.2/lib/node_modules/npm/node_modules/@npmcli/arborist/lib/arborist/build-ideal-tree.js:91
7:11)
95 verbose stack     at async Arborist.buildIdealTree (/nix/store/4bgg8j8275adawqbc5rkm4fv48dgg2i3-nodejs-18.18.2/lib/node_modules/npm/node_modules/@npmcli/arborist/lib/arborist/build-ideal-
tree.js:196:7)
95 verbose stack     at async Promise.all (index 1)
95 verbose stack     at async Arborist.reify (/nix/store/4bgg8j8275adawqbc5rkm4fv48dgg2i3-nodejs-18.18.2/lib/node_modules/npm/node_modules/@npmcli/arborist/lib/arborist/reify.js:159:5)
95 verbose stack     at async Install.exec (/nix/store/4bgg8j8275adawqbc5rkm4fv48dgg2i3-nodejs-18.18.2/lib/node_modules/npm/lib/commands/install.js:149:5)
96 verbose cwd /build/source
97 verbose Linux 5.15.133.1-microsoft-standard-WSL2
98 verbose node v18.18.2
99 verbose npm  v9.8.1
100 error code ENOTCACHED
101 error request to https://registry.npmjs.org/cors failed: cache mode is 'only-if-cached' but no cached response is available.
102 verbose exit 1
103 timing npm Completed in 5429ms
104 verbose unfinished npm timer reify 1700565045406
105 verbose unfinished npm timer reify:loadTrees 1700565045408
106 verbose code 1
107 error A complete log of this run can be found in: /build/.npm/_logs/2023-11-21T11_10_45_160Z-debug-0.log
```

**Comment by adisbladis** [comment]
With 80b4a3ce77294f4606a98ebac90c032b9ec0804c the situation has improved.
The stage where I do `npm install` now succeeds, but the `npm rebuild` stage fails on a script  trying to clone an electron github repo.

**Comment by adisbladis** [comment]
I cobbled together:
``` nix
stdenv.mkDerivation {
  pname = "bitwarden-web";
  version = "2023.10.1";

  src = ./.;

  nodeModules = buildNodeModules.fetchNodeModules {
    packageRoot = ./.;
  };

  nativeBuildInputs = [
    buildNodeModules.hooks.npmConfigHook
    nodejs
    nodejs.passthru.python
    npmHooks.npmBuildHook
    npmHooks.npmInstallHook
  ];

  env.ELECTRON_SKIP_BINARY_DOWNLOAD = "1";

  npmBuildScript = "build:oss:selfhost:prod";
  npmWorkspace = "apps/web";
}
``` 
which builds.

**Comment by SuperSandro2000** [comment]
> but the `npm rebuild` stage fails on a script trying to clone an electron github repo.

>   env.ELECTRON_SKIP_BINARY_DOWNLOAD = "1";

That's fine, we want to use a electron from nixpkgs anyway.

Thanks!
